name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #Building the Js-File
      - name: Build the file
        run: |
          cd /home/runner/work/power-distribution-card/power-distribution-card
          yarn install
          npm run rollup
      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/energy-line-gauge/energy-line-gauge/dist/energy-line-gauge.js
          asset_name: energy-line-gauge.js
          tag: ${{ github.ref }}
          overwrite: true